version: '3.9'

services:
  web_flask:
    build: ./web
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mqtt_mosquitto

  mqtt_mosquitto:
    build: ./mqtt
    container_name: mosquitto
    ports:
      - "11884:11884"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always
    command: mosquitto -c /mosquitto/config/mosquitto.conf

volumes:
  mosquitto_data:
  mosquitto_log:
